---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-demo
  name: deployment-eks-demo
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-eks-demo
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-eks-demo
    spec:
      containers:
      - image: 505874605366.dkr.ecr.us-east-1.amazonaws.com/fluxcd-eks
        imagePullPolicy: Always
        name: app-eks-demo
        ports:
        - containerPort: 80
